### ISSUE TITLE
Problems with the docker container

### ISSUE THREAD

**Issue by lagunenkiter** [brutella/hkknx-public#341]
Hi,

i struggle with the new Docker Image on my Ubuntu 24 Server. I tried several configurations but I am not able to run the Image without errors. 

I have always the folding Error:

_Usage of hkknx:
      --autoupdate   Auto updating the app every 24 hours. (default true)
      --db string    Path to database folder
      --port int     Port of the server (default 8080)
      --verbose      Enable verbose logging
      --version      Prints the version number
invalid argument "${PORT}" for "--port" flag: strconv.ParseInt: parsing "${PORT}": invalid syntax_

I run all my Containers with Portainer and setup an own Stack for HKKNX. 

I used the following configuration:

```yaml
# compose.yaml
services:
  hkknx:
    container_name: "hkknx"
    volumes:
      - /srv/docker/hkknx/db:/db
    hostname: "hkknx"
    image: "brutella/hkknx:3.0.0"
    network_mode: "host"
    # Mapping ports is not needed if "network_mode" is "host".
    ports:
      - "8080:8080/tcp"
    #   - "3671:3671/udp"
    #   - "5353:5353/udp"
    restart: "unless-stopped"
```
But also try several other configuration with and without the Ports and different Port as well as network_mode. 

I have also tried starting directly via Docker to check the Port topic, but unlike with my other containers, I am not able to even start the container (with sudo and without): 

@mim:/srv/docker/hkknx$ sudo docker run --volume /srv/docker/hkknx/db:/db --net=host --restart unless-stopped brutella/hkknx:3.0.0
docker: Error response from daemon: error while creating mount source path '/srv/docker/hkknx/db': mkdir /srv/docker: read-only file system.
@mim:/srv/docker/hkknx$ sudo docker run --volume ./db:/db --net=host --restart unless-stopped brutella/hkknx:3.0.0
docker: Error response from daemon: error while creating mount source path '/srv/docker/hkknx/db': mkdir /srv/docker: read-only file system.

Das File System ist RW und ich kann auch selber Ordner anlegen. 

Hintergrund der ganzen Docker Test ist die Tatsache, dass ich seit dem Upgrade auf Ubuntu 24 nach ein zwei Minuten Betrieb die HomeKit Verbindung verliere und etwas später auch die KNX. Homebridge läuft ohne Probleme im Container. 

Viele Grüße

Lagunenkiter
